name: Build and deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  call-dokploy-template:
    uses: musicorum-app/gh-actions/.github/workflows/dokploy-deploy.yml@main
    secrets: inherit
